---
# tasks file for app

- name: Check for OS support
  fail:
    msg: "OS is not supported"
  when: ansible_os_family != 'RedHat'

- block:
    - set_fact:
        deploy: "{{ lookup('pipe', 'curl -m2 -s {{ app_remote_web }}/{{ inventory_hostname }}') }}"
  rescue:
    - set_fact:
        deploy: True

- include: deploy.yml
  when: deploy
  register: deployed

- fail:
    msg: "Deployment to {{ inventory_hostname }} was not permitted by policy"
  when: deployed|skipped
