---
# tasks file for disk

- name: Find large files
  command: /bin/find "{{ disk_path | default('/tmp') }}" -size +{{ disk_min_size_check | default('5') }}M -ls
  register: output

- name: Output
  debug:
    var: output.stdout_lines
  when: output.stdout != ''
